project:
  type: website
  output-dir: docs

website:
  description: "Blog personal de Daniel M.  A veces escribo desde alta mar. Otras desde tierra. Geek a bordo."
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Daniel Menéndez"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - lumen
    css: styles.css



