project:
  type: website
  output-dir: docs

website:
  description: "Blog personal de Daniel M.  A veces desde alta mar. Otras desde tierra. Geek a bordo."
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Daniel Menéndez"
  navbar:
    right:
      - href: home.qmd
        text: Inicio
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

  page-footer:
    background: light # or `dark` or omit this option altogether (footer color will match page body color)
    left: Copyright ©2026, Daniel Menéndez
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}
format:
  html:
    theme:
      - lumen
    css: styles.css



