---
title: "La Primera Vez"
format: html
---

# Toda avante

La verdad es que si lo pienso bien. No sé cuántas veces lo he empezado, pero nunca he seguido.

De esta me he prometido que va la definitiva. Hace 12 años me saqué el título de Patrones de Embarcaciones de Recreo, y no he dejado la mar. Empecé a colaborar con el Real Club Astur de Regatas antes de cumplir los 18, y al poco de cumplirlos, ya era entrenador del equipo infantil de regatas del mismo club que me había visto crecer y aprender a navegar.

Tras unos años trabajando mientras cursaba los estudios de Grado en Náutica y Transporte Marítimo, me fui primero a trabajar a Salvamento Marítimo como marinero en una Unidad de Salvamento y Rescate. Poco después volvería a mi ciudad para incorporarme como becario en el Área de Maniobra y Navegación, un área dedicada fundamentalmente a la enseñanza.

Y de seguido empezaría mi historia en el mundo de la industria de las operaciones mar adentro. De la mano de Boskalis me convertí en Piloto de Segunda de la Marina Mercante.

Ahora ha llegado la hora de empezar a compartir un poco de lo aprendido. No sólo por enseñar, sino para aprender yo también. De otros y con otros. De ahí nace este blog en Quarto, y el libro *Magistral - Patrón de Embarcaciones de Recreo*, también en Quarto. Magistral porque, cómo la magistral de un barco, me gustaría que fuera referencia de quienes quieran superar con éxito el examen teórico, a la vez que se preparan para ser unos buenos navegantes. Magistral también porque es el ejercicio del magisterio el que me ha traído hasta aquí.

Esta vez no se quedará sólo en palabras.

Continuará...